# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/semtex99/vita/samples/cybershot-PSVita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/semtex99/vita/samples/cybershot-PSVita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/semtex99/vita/samples/cybershot-PSVita/CMakeFiles /home/semtex99/vita/samples/cybershot-PSVita/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/semtex99/vita/samples/cybershot-PSVita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cybershot.vpk

# Build rule for target.
cybershot.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cybershot.vpk
.PHONY : cybershot.vpk

# fast build rule for target.
cybershot.vpk/fast:
	$(MAKE) -f CMakeFiles/cybershot.vpk.dir/build.make CMakeFiles/cybershot.vpk.dir/build
.PHONY : cybershot.vpk/fast

#=============================================================================
# Target rules for targets named cybershot.self

# Build rule for target.
cybershot.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cybershot.self
.PHONY : cybershot.self

# fast build rule for target.
cybershot.self/fast:
	$(MAKE) -f CMakeFiles/cybershot.self.dir/build.make CMakeFiles/cybershot.self.dir/build
.PHONY : cybershot.self/fast

#=============================================================================
# Target rules for targets named cybershot

# Build rule for target.
cybershot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cybershot
.PHONY : cybershot

# fast build rule for target.
cybershot/fast:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/build
.PHONY : cybershot/fast

home/semtex99/vita/samples/common/debugScreen.obj: home/semtex99/vita/samples/common/debugScreen.c.obj

.PHONY : home/semtex99/vita/samples/common/debugScreen.obj

# target to build an object file
home/semtex99/vita/samples/common/debugScreen.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/home/semtex99/vita/samples/common/debugScreen.c.obj
.PHONY : home/semtex99/vita/samples/common/debugScreen.c.obj

home/semtex99/vita/samples/common/debugScreen.i: home/semtex99/vita/samples/common/debugScreen.c.i

.PHONY : home/semtex99/vita/samples/common/debugScreen.i

# target to preprocess a source file
home/semtex99/vita/samples/common/debugScreen.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/home/semtex99/vita/samples/common/debugScreen.c.i
.PHONY : home/semtex99/vita/samples/common/debugScreen.c.i

home/semtex99/vita/samples/common/debugScreen.s: home/semtex99/vita/samples/common/debugScreen.c.s

.PHONY : home/semtex99/vita/samples/common/debugScreen.s

# target to generate assembly for a file
home/semtex99/vita/samples/common/debugScreen.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/home/semtex99/vita/samples/common/debugScreen.c.s
.PHONY : home/semtex99/vita/samples/common/debugScreen.c.s

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/main.c.s
.PHONY : src/main.c.s

src/sprites/sprites.obj: src/sprites/sprites.c.obj

.PHONY : src/sprites/sprites.obj

# target to build an object file
src/sprites/sprites.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/sprites/sprites.c.obj
.PHONY : src/sprites/sprites.c.obj

src/sprites/sprites.i: src/sprites/sprites.c.i

.PHONY : src/sprites/sprites.i

# target to preprocess a source file
src/sprites/sprites.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/sprites/sprites.c.i
.PHONY : src/sprites/sprites.c.i

src/sprites/sprites.s: src/sprites/sprites.c.s

.PHONY : src/sprites/sprites.s

# target to generate assembly for a file
src/sprites/sprites.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/sprites/sprites.c.s
.PHONY : src/sprites/sprites.c.s

src/system/control_input.obj: src/system/control_input.c.obj

.PHONY : src/system/control_input.obj

# target to build an object file
src/system/control_input.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/control_input.c.obj
.PHONY : src/system/control_input.c.obj

src/system/control_input.i: src/system/control_input.c.i

.PHONY : src/system/control_input.i

# target to preprocess a source file
src/system/control_input.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/control_input.c.i
.PHONY : src/system/control_input.c.i

src/system/control_input.s: src/system/control_input.c.s

.PHONY : src/system/control_input.s

# target to generate assembly for a file
src/system/control_input.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/control_input.c.s
.PHONY : src/system/control_input.c.s

src/system/timing.obj: src/system/timing.c.obj

.PHONY : src/system/timing.obj

# target to build an object file
src/system/timing.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/timing.c.obj
.PHONY : src/system/timing.c.obj

src/system/timing.i: src/system/timing.c.i

.PHONY : src/system/timing.i

# target to preprocess a source file
src/system/timing.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/timing.c.i
.PHONY : src/system/timing.c.i

src/system/timing.s: src/system/timing.c.s

.PHONY : src/system/timing.s

# target to generate assembly for a file
src/system/timing.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/system/timing.c.s
.PHONY : src/system/timing.c.s

src/toolbox/drawing.obj: src/toolbox/drawing.c.obj

.PHONY : src/toolbox/drawing.obj

# target to build an object file
src/toolbox/drawing.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/drawing.c.obj
.PHONY : src/toolbox/drawing.c.obj

src/toolbox/drawing.i: src/toolbox/drawing.c.i

.PHONY : src/toolbox/drawing.i

# target to preprocess a source file
src/toolbox/drawing.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/drawing.c.i
.PHONY : src/toolbox/drawing.c.i

src/toolbox/drawing.s: src/toolbox/drawing.c.s

.PHONY : src/toolbox/drawing.s

# target to generate assembly for a file
src/toolbox/drawing.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/drawing.c.s
.PHONY : src/toolbox/drawing.c.s

src/toolbox/toolbox.obj: src/toolbox/toolbox.c.obj

.PHONY : src/toolbox/toolbox.obj

# target to build an object file
src/toolbox/toolbox.c.obj:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/toolbox.c.obj
.PHONY : src/toolbox/toolbox.c.obj

src/toolbox/toolbox.i: src/toolbox/toolbox.c.i

.PHONY : src/toolbox/toolbox.i

# target to preprocess a source file
src/toolbox/toolbox.c.i:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/toolbox.c.i
.PHONY : src/toolbox/toolbox.c.i

src/toolbox/toolbox.s: src/toolbox/toolbox.c.s

.PHONY : src/toolbox/toolbox.s

# target to generate assembly for a file
src/toolbox/toolbox.c.s:
	$(MAKE) -f CMakeFiles/cybershot.dir/build.make CMakeFiles/cybershot.dir/src/toolbox/toolbox.c.s
.PHONY : src/toolbox/toolbox.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cybershot.vpk"
	@echo "... cybershot.self"
	@echo "... cybershot"
	@echo "... home/semtex99/vita/samples/common/debugScreen.obj"
	@echo "... home/semtex99/vita/samples/common/debugScreen.i"
	@echo "... home/semtex99/vita/samples/common/debugScreen.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sprites/sprites.obj"
	@echo "... src/sprites/sprites.i"
	@echo "... src/sprites/sprites.s"
	@echo "... src/system/control_input.obj"
	@echo "... src/system/control_input.i"
	@echo "... src/system/control_input.s"
	@echo "... src/system/timing.obj"
	@echo "... src/system/timing.i"
	@echo "... src/system/timing.s"
	@echo "... src/toolbox/drawing.obj"
	@echo "... src/toolbox/drawing.i"
	@echo "... src/toolbox/drawing.s"
	@echo "... src/toolbox/toolbox.obj"
	@echo "... src/toolbox/toolbox.i"
	@echo "... src/toolbox/toolbox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

